FROM    ubuntu:latest

RUN     apt update && \
        apt install -y apache2 wget && \
        rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

RUN     wget https://es.wordpress.org/latest-es_ES.tar.gz -P /tmp && \
        tar zxfv /tmp/latest-es_ES.tar.gz -C /tmp && \
        mv /tmp/wordpress/* /var/www/html/ && \
        rm -fR /tmp/* 

EXPOSE  80

CMD [ "/etc/init.d/apache2","start"]
